export const ADD_RAW_MATERIAL_PURCHASE = "ADD_RAW_MATERIAL_PURCHASE";
export const GET_MASTER_DATA = "GET_MASTER_DATA";
export const GET_RAW_MATERIAL_PURCHASE= "GET_RAW_MATERIAL_PURCHASE";
export const ADD_ORDER = "ADD_ORDER";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";